version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/clean_docker.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/restart_docker.sh
      timeout: 300
      runas: ec2-user
